### ISSUE TITLE
Please ask about the string in the running process

### ISSUE THREAD

**Issue by JiuYanQ** [yzj2019/k_anonymity#1]
C:\Users\DELL\AppData\Local\Programs\Python\Python36\python.exe G:/test/k_anonymity-main/test2.py
Traceback (most recent call last):
  File "G:/test/k_anonymity-main/test2.py", line 13, in <module>
    script, path, k = argv[0], argv[1], argv[2]
IndexError: list index out of range

Hello, blogger. Recently, I tried to understand this knowledge. The above problems occurred when running your code. I found some methods on the Internet and still failed to solve them. May I ask if the blogger has encountered this problem and how to solve it? Thank you.Or is it convenient to add a contact information? I'd like to ask. This is my email 2254153510@qq.com.

**Comment by yzj2019** [comment]
“argv” means args passed in from the command line, maybe you missed any?
I need more details like the environment or the command you ran.

**Comment by JiuYanQ** [comment]
I use pycharm. Here's the screenshot of the environment configuration. Please take a look. Thank you.







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yzj2019/k_anonymity"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月26日(星期二) 晚上9:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yzj2019/k_anonymity] Please ask about the string in the running process (Issue #1)





 
“argv” means args passed in from the command line, maybe you missed any?
 I need more details like the environment or the command you ran.

**Comment by yzj2019** [comment]
I can't see your screenshot 0.0

**Comment by yzj2019** [comment]
> I use pycharm. Here's the screenshot of the environment configuration. Please take a look. Thank you.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "yzj2019/k_anonymity" ***@***.***&gt;; 发送时间:&nbsp;2022年4月26日(星期二) 晚上9:26 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [yzj2019/k_anonymity] Please ask about the string in the running process (Issue #1) “argv” means args passed in from the command line, maybe you missed any? I need more details like the environment or the command you ran. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

I can't see your screenshot 0.0

**Comment by JiuYanQ** [comment]
Sorry, it may have been uploaded in the wrong way. Can I communicate with you in Chinese?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yzj2019/k_anonymity"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月26日(星期二) 晚上9:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yzj2019/k_anonymity] Please ask about the string in the running process (Issue #1)





  
I use pycharm. Here's the screenshot of the environment configuration. Please take a look. Thank you.
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "yzj2019/k_anonymity" @.&gt;; 发送时间:&nbsp;2022年4月26日(星期二) 晚上9:26 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [yzj2019/k_anonymity] Please ask about the string in the running process (Issue #1) “argv” means args passed in from the command line, maybe you missed any? I need more details like the environment or the command you ran. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
I can't see your screenshot 0.0

**Comment by yzj2019** [comment]
> Sorry, it may have been uploaded in the wrong way. Can I communicate with you in Chinese?
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "yzj2019/k_anonymity" ***@***.***&gt;; 发送时间:&nbsp;2022年4月26日(星期二) 晚上9:46 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [yzj2019/k_anonymity] Please ask about the string in the running process (Issue #1) I use pycharm. Here's the screenshot of the environment configuration. Please take a look. Thank you. … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "yzj2019/k_anonymity" @.&gt;; 发送时间:&nbsp;2022年4月26日(星期二) 晚上9:26 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [yzj2019/k_anonymity] Please ask about the string in the running process (Issue #1) “argv” means args passed in from the command line, maybe you missed any? I need more details like the environment or the command you ran. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; I can't see your screenshot 0.0 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

okk说中文吧hhh

**Comment by JiuYanQ** [comment]
脑仁都大了，刚刚接触这个东西，代码基础又不过关，所以问题有点点那个啥，所以打扰了，GitHub上只能英文留言，头秃




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yzj2019/k_anonymity"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月26日(星期二) 晚上9:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yzj2019/k_anonymity] Please ask about the string in the running process (Issue #1)





  
Sorry, it may have been uploaded in the wrong way. Can I communicate with you in Chinese?
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "yzj2019/k_anonymity" @.&gt;; 发送时间:&nbsp;2022年4月26日(星期二) 晚上9:46 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [yzj2019/k_anonymity] Please ask about the string in the running process (Issue #1) I use pycharm. Here's the screenshot of the environment configuration. Please take a look. Thank you. … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "yzj2019/k_anonymity" @.&gt;; 发送时间:&nbsp;2022年4月26日(星期二) 晚上9:26 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [yzj2019/k_anonymity] Please ask about the string in the running process (Issue #1) “argv” means args passed in from the command line, maybe you missed any? I need more details like the environment or the command you ran. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; I can't see your screenshot 0.0 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt;
  
okk说中文吧hhh

**Comment by yzj2019** [comment]
“script, path, k = argv[0], argv[1], argv[2]”
测试程序需要接受两个命令行参数，path代表*.data文件的路径，k代表参数k的值；
我没用过pycharm，不知道pycharm怎么带参数执行 0.0

**Comment by JiuYanQ** [comment]
你是用的什么呀，我看我有吗
没有的话我去研究一下pycharm的
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yzj2019/k_anonymity"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月26日(星期二) 晚上10:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yzj2019/k_anonymity] Please ask about the string in the running process (Issue #1)





 
“script, path, k = argv[0], argv[1], argv[2]”
 测试程序需要接受两个命令行参数，path代表*.data文件的路径，k代表参数k的值；
 我没用过pycharm，不知道pycharm怎么带参数执行 0.0

**Comment by yzj2019** [comment]
我用的是vscode，你去找一下pycharm的吧，应该不难

**Comment by JiuYanQ** [comment]
嗯嗯，了解啦，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yzj2019/k_anonymity"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月26日(星期二) 晚上10:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yzj2019/k_anonymity] Please ask about the string in the running process (Issue #1)





 
我用的是vscode，你去找一下pycharm的吧，应该不难
